# Generated by Django 5.2.8 on 2025-11-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор аллергена')),
                ('name', models.TextField(verbose_name='Название аллергена')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('login', models.TextField(max_length=100, unique=True, verbose_name='Логин')),
                ('hashed_password', models.TextField(verbose_name='Зашифрованный пароль')),
                ('date_registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор блюда')),
                ('name', models.TextField(max_length=100, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание и комментарии к блюду')),
                ('calories', models.FloatField(verbose_name='Калории')),
                ('proteins', models.FloatField(verbose_name='Белки')),
                ('fats', models.FloatField(verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
                ('url', models.URLField(verbose_name='Ссылка на рецепт')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления блюда')),
                ('allergens', models.ManyToManyField(to='main.allergen', verbose_name='Аллергены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
