# Generated by Django 5.2.8 on 2025-12-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user', verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='allergen',
            name='is_global',
            field=models.BooleanField(default=True, verbose_name='Глобальный аллерген'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='allergen',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', False)), fields=('name', 'created_by'), name='unique_user_allergen'),
        ),
        migrations.AddConstraint(
            model_name='allergen',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('name',), name='unique_global_allergen'),
        ),
    ]
