# Generated by Django 5.2.8 on 2025-12-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allergen_created_by_allergen_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
