# Generated by Django 5.2.8 on 2025-11-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_allergen_id_alter_dish_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, to='main.allergen', verbose_name='Аллергены'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание и комментарии к блюду'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fats',
            field=models.FloatField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='proteins',
            field=models.FloatField(blank=True, null=True, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на рецепт'),
        ),
    ]
