# Generated by Django 6.0 on 2025-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dish_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dish_photos/%Y/%m/%d/', verbose_name='Фотография блюда'),
        ),
    ]
